let test = {
  created: 1601814602000,
  duration: 118800000,
  id: "273702584",
  name: "Devfest Casablanca x Settat 2020",
  date_in_series_pattern: false,
  status: "upcoming",
  time: 1602842400000,
  local_date: "2020-10-16",
  local_time: "11:00",
  updated: 1601814603000,
  utc_offset: 3600000,
  waitlist_count: 0,
  yes_rsvp_count: 1,
  is_online_event: false,
  group: {
    created: 1499254081000,
    name: "GDG Settat",
    id: 24842408,
    join_mode: "open",
    lat: 33.0099983215332,
    lon: -7.619999885559082,
    urlname: "GDG-Settat",
    who: "Members",
    localized_location: "Sattat, Morocco",
    state: "",
    country: "ma",
    region: "en_US",
    timezone: "Africa/Casablanca",
  },
  link: "https://www.meetup.com/GDG-Settat/events/273702584/",
  description:
    '<p>PLEASE RSVP USING THE LINK BELOW</p> <p>&lt;br/&gt;<a href="https://gdg.community.dev/events/details/google-gdg-settat-presents-devfest-casablanca-x-settat-2020-1/" class="linkified">https://gdg.community.dev/events/details/google-gdg-settat-presents-devfest-casablanca-x-settat-2020-1/</a></p> <p>&amp;lt;p&amp;gt;Devfest season is here. This year, we are organizing devfest Casablanca x settat online.&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;More details will be shared soon.&amp;lt;/p&amp;gt;&lt;/p&gt;</p> <p>Agenda&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>&lt;br/&gt;---&lt;br/&gt;</p> <p>&lt;br/&gt;<br/>Hosted By&lt;br/&gt;</p> <p>Abderrahman Jaize, GDG Organizer&lt;br/&gt;</p> <p>Data Scientist | Machine Learning | Deep Learning | NLP | Python | Computer vision | PhD student.&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>ABDELLAH JAIZE, GDG Organizer&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>Jihane Majdoul, GDG Organizer&lt;br/&gt;</p> <p>Software Engineer - Machine Learning-Business Intelligence -WomenTechmakers-IamRemarkable facilitator-&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>Achraf Lebbarki, GDG Organizer&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>Mohammed FAKHAM, GDG Organizer&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>Siham Bendaia, GDG Organizer&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>salma elbakkal, Event Organizer&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>yassine elmahi, Assistant Organizer&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>EL MOUKTAFI MOHAMED, Assistant Orginizer&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>Mounia El koraichi, Assistant Orginizer&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>BOCHRA LABIAD, Assistant Orginizer&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>&lt;br/&gt;---&lt;br/&gt;</p> <p>&lt;br/&gt;<br/>Partner&lt;br/&gt;</p> <p>FVA (<a href="https://www.fva.ma)&lt;br/&gt" class="linkified">https://www.fva.ma)&lt;br/&gt</a>;<br/>&lt;br/&gt;<br/>&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>&lt;br/&gt;---&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>PLEASE RSVP USING THE LINK BELOW</p> <p>&lt;br/&gt;<a href="https://gdg.community.dev/events/details/google-gdg-settat-presents-devfest-casablanca-x-settat-2020-1/" class="linkified">https://gdg.community.dev/events/details/google-gdg-settat-presents-devfest-casablanca-x-settat-2020-1/</a></p> ',
  visibility: "public",
  member_pay_fee: false,
};
